<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>in.virit.sb</groupId>
        <artifactId>viritin-addon-project-parent</artifactId>
        <version>0.0.9</version>
        <relativePath/>
    </parent>
    <groupId>in.virit</groupId>
    <artifactId>webbluetooth-drivers</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <name>webbluetooth-drivers</name>
    <packaging>pom</packaging>
    <organization>
        <name>Vaadin Community</name>
    </organization>
    <properties>
        <spring.boot.version>4.0.4</spring.boot.version>
        <vaadin.version>25.1.0</vaadin.version>
        <github.account>viritin</github.account>
        <github.project>webbluetooth-drivers</github.project>
    </properties>
    <scm>
        <url>https://github.com/${github.account}/${github.project}</url>
        <connection>scm:git:git://github.com/${github.account}/${github.project}.git</connection>
        <developerConnection>scm:git:ssh://git@github.com:/${github.account}/${github.project}.git</developerConnection>
    </scm>
    <issueManagement>
        <system>GitHub</system>
        <url>https://github.com/${github.account}/${github.project}/issues</url>
    </issueManagement>
    <licenses>
        <license>
            <name>Apache 2</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <modules>
        <module>ble-label-common</module>
        <module>phomemo-driver</module>
        <module>wozinsky-wik-10</module>
        <module>dymo-letratag-200b</module>
        <!--
        Demo/Test apps, built independently
        <module>label-printer-demo</module>
        <module>rpi-letra-example</module>
        -->
    </modules>
</project>
